# Generated by Django 4.1.1 on 2022-10-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_alter_food_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dietaryFibre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
