# Generated by Django 4.1.1 on 2022-10-20 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weightPerMeal', models.CharField(max_length=200)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('saturatedFat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transFat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminB1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminB2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitaminB3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealTime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WeightType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightType', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.food')),
                ('mealTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.mealtime')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='foodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.foodtype'),
        ),
        migrations.AddField(
            model_name='food',
            name='weightType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calorie.weighttype'),
        ),
    ]
