# Generated by Django 4.1.1 on 2022-10-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_alter_foodtype_options_alter_mealtime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
