# Generated by Django 4.1.1 on 2022-10-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_alter_food_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
