# Generated by Django 4.1.1 on 2022-10-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0005_food_dietaryfibre'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
